-- ============================================================================
-- 63. Crops register + crop-wise, effective-dated location rates
-- ----------------------------------------------------------------------------
-- * crops: a register (auto number + name), selected via dropdown everywhere.
-- * location_crop_rates: farmer & client rate per (location, crop) effective from
--   a cutoff date. A rate change = a new row with a later effective_from; the
--   resolver never uses an older rate on/after that date. crop_id NULL = the
--   location's all-crops default.
-- * location_rate_on(location, crop, date) resolves the rate in force.
-- Additive.
-- ============================================================================

create table if not exists public.crops (
  id         uuid primary key default gen_random_uuid(),
  crop_no    integer generated by default as identity,
  name       text not null,
  active     boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);
create unique index if not exists crops_name_uk on public.crops(lower(btrim(name)));

create table if not exists public.location_crop_rates (
  id             uuid primary key default gen_random_uuid(),
  location_id    uuid not null references public.spray_locations(id) on delete cascade,
  crop_id        uuid references public.crops(id) on delete cascade,  -- NULL = all-crops default
  farmer_rate    numeric,
  client_rate    numeric,
  effective_from date not null default current_date,
  note           text,
  created_by     uuid references public.profiles(id),
  created_at     timestamptz not null default now()
);
create index if not exists lcr_loc_idx on public.location_crop_rates(location_id, effective_from);

alter table public.acre_entries add column if not exists crop_id uuid references public.crops(id);

-- Rate in force for a location/crop on a date: the latest effective_from that is
-- on/before the date, preferring a crop-specific row over the all-crops default,
-- then falling back to the location's base rates.
create or replace function public.location_rate_on(p_location uuid, p_crop uuid, p_date date)
returns table(farmer_rate numeric, client_rate numeric)
language sql stable as $$
  with pick as (
    select r.farmer_rate, r.client_rate
      from public.location_crop_rates r
     where r.location_id = p_location
       and (r.crop_id = p_crop or r.crop_id is null)
       and r.effective_from <= coalesce(p_date, current_date)
     order by (case when r.crop_id = p_crop then 0 else 1 end), r.effective_from desc
     limit 1
  )
  select coalesce((select farmer_rate from pick), l.farmer_rate),
         coalesce((select client_rate from pick), l.client_rate)
    from public.spray_locations l where l.id = p_location;
$$;
grant execute on function public.location_rate_on(uuid, uuid, date) to authenticated;

-- RLS: internal read/write, creator/approver delete (mirrors other registers)
do $$ declare t text;
begin
  foreach t in array array['crops','location_crop_rates'] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists %I_read on public.%I;', t, t);
    execute format('create policy %I_read on public.%I for select to authenticated using (true);', t, t);
    execute format('drop policy if exists %I_insert on public.%I;', t, t);
    execute format('create policy %I_insert on public.%I for insert to authenticated with check (public.is_internal());', t, t);
    execute format('drop policy if exists %I_update on public.%I;', t, t);
    execute format('create policy %I_update on public.%I for update to authenticated using (public.is_internal());', t, t);
    execute format('drop policy if exists %I_delete on public.%I;', t, t);
    execute format('create policy %I_delete on public.%I for delete to authenticated using (public.has_role(array[''admin'',''approver'']::user_role[]) or created_by = auth.uid());', t, t);
  end loop;
end $$;

grant select, insert, update, delete on public.crops, public.location_crop_rates to authenticated;
grant usage, select on all sequences in schema public to authenticated;
